show_author_in_topic_lists:
  type: bool
  default: false
  description:
    en: "Show the topic author instead of last poster in all topic lists. Disabled shows the last poster (not multiple participants)."
poster_column_placement:
  type: enum
  default: "Default"
  choices:
    - Default
    - First
    - Last
  description:
    en: "Poster column placement in all topic list pages."
show_username_instead:
  type: bool
  default: false
  description:
    en: "Show poster usernames instead profile avatars in all topic list pages."
